---
name: Run Yamllint
# yamllint disable-line rule:truthy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: 'Checkout'
        uses: actions/checkout@master        
      - name: Lint and Check
        run: "${GITHUB_WORKSPACE}/run_linter.sh"
        env:
          CLANG_FORMAT: "/usr/bin/clang-format-10"
          GITHUB_ACCESS_TOKEN: ${{ secrets.GHP }}
